#!/bin/sh

if [ -z "$*" ];then
    echo "No command specified"
    exit 1
fi
hosts=$(echo "m75s-1 m75s-2 m75s-3" | sed -e "s/$(hostname -s)//")
for h in $hosts $(hostname -s);do echo "=== root@$h ===";ssh root@$h $@;done
