#!/bin/sh
mount_points="/root/gluster /var/lib/libvirt/images /var/lib/libvirt/images2"


usage() {
    echo "Usage: cluster COMMAND"
    echo ""
    echo "COMMAND:"
    echo "    status: Show filesystem and pacemaker status"
    echo "    start: Mount filesystem and start pacemaker"
    echo "    stop: Standby all nodes and unmount filesystem"
    echo "    unstandby: Unstandby all nodes"
    echo "    reboot: Reboot a node"
    echo "    poweroff: Poweroff a node"
    echo ""
}

if [ -z "$1" ];then
    usage
    exit 1
fi

if [ $1 = "start" ];then
    
    for point in $mount_points;do
	while true;do
	    logger "Mounting $point"
	    result=$(mount $point 2>&1)
	    if [ $? = 0 -o $? = 32 ];then
		break
	    else
		logger "$result"
	    fi
	    sleep 5
	done
    done
    systemctl start pacemaker.service
    if [ -f /root/.unstandby ];then
	while true;do
	    sleep 5
	    /usr/sbin/pcs node unstandby --wait >/dev/null 2>&1
	    if [ $? = 0 ];then
		rm /root/.unstandby
		break
	    fi
	done
    fi
elif [ $1 = "stop" ];then
    /usr/sbin/pcs node standby --all
    allssh cp -f /root/bin/allssh /tmp/
    allssh cp -f /root/bin/cluster /tmp/
    for point in $mount_points;do
	/tmp/allssh 'false;while [ $? != 0 -a $? != 32 ];do umount "'$point'";sleep 1;done;echo "'$point' unmounted"' &
    done
elif [ $1 = "unstandby" ];then
    /usr/sbin/pcs node unstandby --all
elif [ $1 = "reboot" -o $1 = "poweroff" ];then
    is_healing=$(for vol in $(gluster volume list);do gluster volume heal $vol info | grep "Number of entries:" | egrep -v "Number of entries: 0|Number of entries: -";done)
    
    if [ -n "$is_healing" ];then
	echo "GlusterFS: Healing"
    else
	echo "GlusterFS: OK"
	pcs node standby --wait
	if [ $? = 0 ];then
	    touch /root/.unstandby
	    systemctl stop glusterd.service
	    killall glusterfsd
	    if [ $1 = "reboot" ];then
		shutdown -r now
	    fi
	    if [ $1 = "poweroff" ];then
		shutdown -h now
	    fi
	else
	    echo "Putting into standby mode failed"
	fi
    fi
elif [ $1 = "status" ];then
    pcs status
    echo ""
    is_healing=$(for vol in $(gluster volume list);do gluster volume heal $vol info | grep "Number of entries:" | egrep -v "Number of entries: 0|Number of entries: -";done)
    if [ -n "$is_healing" ];then
	echo "GlusterFS: Healing"
    else
	echo "GlusterFS: OK"
    fi
else
    usage
    exit 1
fi
